Add fonts as woff
unboxed/ubxd-wagtail pull request #38
Opened 2020-11-12 15:57 UTC by melzreal

2020-11-12 16:16 UTC, siapankina requested changes
Great job! When this is merged, implementing fonts will be much easier

2020-11-12 16:17 UTC, siapankina requested changes

2020-11-12 16:17 UTC, siapankina commented on unboxed/static/css/blog_page.css
> -	width: 66%;
can you please bring width back? we need it to keep the text no wider than 66%

2020-11-12 18:09 UTC, melzreal commented on unboxed/static/css/blog_page.css
> -	width: 66%;
no because this limits the width of the container, not just the font. There is nothing as well on the design suggesting the fonts should only be on half the page? This is full width:

![image](https://user-images.githubusercontent.com/9452321/98978551-1496d380-2512-11eb-98fc-6ff8e7f0789e.png)

we shouldn't apply width to fonts, to limit the width of a font in any context we need to be applying it to the surrounding container

2020-11-12 18:10 UTC, melzreal commented on unboxed/static/css/blog_page.css
> -	width: 66%;
you can use left-align on the div if all the effect we're after is to align the content left, or use left align in the css

2020-11-13 10:02 UTC, siapankina approved these changes
Nice job! 🚢 it

2020-11-13 10:39 UTC, merged